### ISSUE TITLE
cannot build against enchant 2.x ?

### ISSUE THREAD

**Issue by kyrios123** [rfk/pyenchant#116]
I tried to build the latest version of pyenchant v1.6.11 against [enchant v2.1.2](https://github.com/AbiWord/enchant/releases/tag/v2.1.2) with both python 2.7 and python 3.5 but the build fails with the following error
```
python3 setup.py build -b __py3_build
Traceback (most recent call last):
  File "setup.py", line 212, in <module>
    import enchant
  File "/home/build/YPKG/root/pyenchant/build/pyenchant-1.6.11/enchant/__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "/home/build/YPKG/root/pyenchant/build/pyenchant-1.6.11/enchant/_enchant.py", line 312, in <module>
    dict_is_in_session1 = e.enchant_dict_is_in_session
  File "/usr/lib/python3.5/ctypes/__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libenchant.so: undefined symbol: enchant_dict_is_in_session

```
Here are the ABI symbols for enchant 2.1.2
```
libenchant.so.2:enchant_broker_describe
libenchant.so.2:enchant_broker_dict_exists
libenchant.so.2:enchant_broker_free
libenchant.so.2:enchant_broker_free_dict
libenchant.so.2:enchant_broker_get_error
libenchant.so.2:enchant_broker_init
libenchant.so.2:enchant_broker_list_dicts
libenchant.so.2:enchant_broker_request_dict
libenchant.so.2:enchant_broker_request_pwl_dict
libenchant.so.2:enchant_broker_set_ordering
libenchant.so.2:enchant_dict_add
libenchant.so.2:enchant_dict_add_to_session
libenchant.so.2:enchant_dict_check
libenchant.so.2:enchant_dict_describe
libenchant.so.2:enchant_dict_free_string_list
libenchant.so.2:enchant_dict_get_error
libenchant.so.2:enchant_dict_get_extra_word_characters
libenchant.so.2:enchant_dict_is_added
libenchant.so.2:enchant_dict_is_removed
libenchant.so.2:enchant_dict_is_word_character
libenchant.so.2:enchant_dict_remove
libenchant.so.2:enchant_dict_remove_from_session
libenchant.so.2:enchant_dict_set_error
libenchant.so.2:enchant_dict_store_replacement
libenchant.so.2:enchant_dict_suggest
libenchant.so.2:enchant_get_conf_dirs
libenchant.so.2:enchant_get_prefix_dir
libenchant.so.2:enchant_get_user_config_dir
libenchant.so.2:enchant_get_user_language
libenchant.so.2:enchant_get_version
libenchant.so.2:enchant_provider_set_error
libenchant.so.2:enchant_pwl_add
libenchant.so.2:enchant_pwl_check
libenchant.so.2:enchant_pwl_free
libenchant.so.2:enchant_pwl_init
libenchant.so.2:enchant_pwl_init_with_file
libenchant.so.2:enchant_pwl_remove
libenchant.so.2:enchant_pwl_suggest
libenchant.so.2:enchant_set_prefix_dir
```

**Comment by jelly** [comment]
The most easy fix would be remove is_in_session since it was already deprecated, PR made here https://github.com/rfk/pyenchant/pull/118

**Comment by awhan** [comment]
I tried installing pyenchant to a virtualenv but pip doesn't install pyenchant any more and throws out the error ` AttributeError: /usr/lib/libenchant.so: undefined symbol: enchant_dict_is_in_session`
Python 3.6.3
Pip 9.0.1

**Comment by rr-** [comment]
This is a showstopper. Please merge @jelly 's changes.

**Comment by rfk** [comment]
Thanks for the fix @jelly, I've released version 2.0.0 with your change.  Please let me know if this doesn't resolve the issue with builds, or introduces any new ones.

**Comment by rr-** [comment]
Works for us, thanks for the prompt response!

**Comment by awhan** [comment]
thanks @jelly and @rfk 2.0.0 works for me too
archlinux 
python 3.6.3
pip 9.0.1

**Comment by kyrios123** [comment]
Works for me too, so I can close this issue, thanks!
