### ISSUE TITLE
A bug with ctypes `_PyUnicode_AsWideCharString` in Python 3.6.3 && uWSGI

### ISSUE THREAD

**Issue by kornov-rooman** [rfk/pyenchant#117]
Hi!

We got a strange bug with combined uWSGI && Django && enchant usage. It seems to be apearing only in Python 3.6.3 with uWSGI usage. Full trace we're getting:
```py3tb
Traceback (most recent call last):
  File "/home/user/PycharmProjects/encha/enchatest/enchatest/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/user/.pyenv/versions/encha/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/user/.pyenv/versions/encha/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/.pyenv/versions/encha/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/user/.pyenv/versions/encha/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/user/.pyenv/versions/3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/PycharmProjects/encha/enchatest/why/models.py", line 2, in <module>
    import enchant
  File "/home/user/.pyenv/versions/encha/lib/python3.6/site-packages/enchant/__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "/home/user/.pyenv/versions/encha/lib/python3.6/site-packages/enchant/_enchant.py", line 52, in <module>
    from ctypes import *
  File "/home/user/.pyenv/versions/3.6.3/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: /home/user/.pyenv/versions/3.6.3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_AsWideCharString
```

[Repository with the bug reproduction](https://github.com/kornov-rooman/uwsgi_enchant_issue)

We catch the bug only when the project's run via uwsgi, when it's run via runserver everything's OK.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
