### ISSUE TITLE
[Bug] Can not begin to use issue

### ISSUE THREAD

**Issue by Kristinita** [rfk/pyenchant#123]
### 1. Summary

I can not begin to use pyenchant in my Windows 64-bit.

Possible duplicates is **#42** and **#92**.

### 2. Settings

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Python 3.6.3,
+ pyenchant 2.0.0.

### 3. Steps to reproduce

I install pyenchant use pip:

```shell
D:\SashaPythonista>pip install pyenchant
Collecting pyenchant
Installing collected packages: pyenchant
Successfully installed pyenchant-2.0.0
```

Now I [**run Python Interpreter**](https://pythonhosted.org/pyenchant/tutorial.html#creating-and-using-dictionary-objects).

```python
>>> import enchant
>>> d = enchant.Dict("en_US")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\enchant\__init__.py", line 562, in __init__
    _EnchantObject.__init__(self)
  File "C:\Python36\lib\site-packages\enchant\__init__.py", line 168, in __init__
    self._init_this()
  File "C:\Python36\lib\site-packages\enchant\__init__.py", line 569, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "C:\Python36\lib\site-packages\enchant\__init__.py", line 310, in _request_dict_data
    self._raise_error(eStr % (tag,),DictNotFoundError)
  File "C:\Python36\lib\site-packages\enchant\__init__.py", line 258, in _raise_error
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'en_US' could not be found
>>> print enchant.list_languages()
  File "<stdin>", line 1
    print enchant.list_languages()
                ^
SyntaxError: invalid syntax
```

I try [**add own dictionary for Russian language**](https://pythonhosted.org/pyenchant/tutorial.html#adding-language-dictionaries). I haven't subfolder `share` in folder `enchant` → I create `share` and next subfolders.

![Own dictionary](https://i.imgur.com/arhLYzV.png)

Same result:

```python
>>> d = enchant.Dict("ru_RU")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\enchant\__init__.py", line 562, in __init__
    _EnchantObject.__init__(self)
  File "C:\Python36\lib\site-packages\enchant\__init__.py", line 168, in __init__
    self._init_this()
  File "C:\Python36\lib\site-packages\enchant\__init__.py", line 569, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "C:\Python36\lib\site-packages\enchant\__init__.py", line 310, in _request_dict_data
    self._raise_error(eStr % (tag,),DictNotFoundError)
  File "C:\Python36\lib\site-packages\enchant\__init__.py", line 258, in _raise_error
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'ru_RU' could not be found
```

Thanks.

**Comment by Julian** [comment]
Your first SyntaxError is you using `print ` on a Py3.6 interpreter.

You either need to use `print(...)` or to switch to Py2.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
