### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by Arfrever** [rfk/pyenchant#20]
5 failures occur with all versions of Python.
3 errors occur only with Python 3.3.
(Test results from git head.)

```
$ PYTHONPATH="build/lib" python3.3 setup.py test
running test
running egg_info
writing pyenchant.egg-info/PKG-INFO
writing dependency_links to pyenchant.egg-info/dependency_links.txt
writing eager_resources to pyenchant.egg-info/eager_resources.txt
writing top-level names to pyenchant.egg-info/top_level.txt
reading manifest file 'pyenchant.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'docs/'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'tools/pyenchant-bdist-win32-sources'
no previously-included directories found matching 'tools/pyenchant-bdist-osx-sources'
writing manifest file 'pyenchant.egg-info/SOURCES.txt'
running build_ext
test_UnicodeInstallPath (enchant.tests.TestInstallEnv)
Test installation in a path containing unicode chars. ... Traceback (most recent call last):
  File "/tmp/tmp5g3508/test_åäö_ing/enchant/__init__.py", line 894, in <module>
    res = enchant.tests.runtestsuite()
  File "/tmp/tmp5g3508/test_åäö_ing/enchant/tests.py", line 613, in runtestsuite
    return unittest.TextTestRunner(verbosity=0).run(buildtestsuite(recurse=recurse))
  File "/usr/lib64/python3.3/unittest/runner.py", line 168, in run
    test(result)
  File "/usr/lib64/python3.3/unittest/suite.py", line 67, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.3/unittest/suite.py", line 105, in run
    test(result)
  File "/usr/lib64/python3.3/unittest/suite.py", line 67, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.3/unittest/suite.py", line 105, in run
    test(result)
  File "/usr/lib64/python3.3/unittest/case.py", line 492, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.3/unittest/case.py", line 452, in run
    result.addFailure(self, exc_info)
  File "/usr/lib64/python3.3/unittest/runner.py", line 75, in addFailure
    super(TextTestResult, self).addFailure(test, err)
  File "/usr/lib64/python3.3/unittest/result.py", line 17, in inner
    return method(self, *args, **kw)
  File "/usr/lib64/python3.3/unittest/result.py", line 121, in addFailure
    self.failures.append((test, self._exc_info_to_string(err, test)))
  File "/usr/lib64/python3.3/unittest/result.py", line 160, in _exc_info_to_string
    msgLines = traceback.format_exception(exctype, value, tb, length)
  File "/usr/lib64/python3.3/traceback.py", line 187, in format_exception
    list.extend(format_tb(tb, limit))
  File "/usr/lib64/python3.3/traceback.py", line 75, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/usr/lib64/python3.3/traceback.py", line 100, in extract_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib64/python3.3/linecache.py", line 15, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib64/python3.3/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib64/python3.3/linecache.py", line 126, in updatecache
    with tokenize.open(fullname) as fp:
AttributeError: 'module' object has no attribute 'open'
FAIL
test_basic (enchant.tests.TestInstallEnv)
Test proper functioning of TestInstallEnv suite. ... Traceback (most recent call last):
  File "/tmp/tmpu9b95v/build/enchant/__init__.py", line 894, in <module>
    res = enchant.tests.runtestsuite()
  File "/tmp/tmpu9b95v/build/enchant/tests.py", line 613, in runtestsuite
    return unittest.TextTestRunner(verbosity=0).run(buildtestsuite(recurse=recurse))
  File "/usr/lib64/python3.3/unittest/runner.py", line 168, in run
    test(result)
  File "/usr/lib64/python3.3/unittest/suite.py", line 67, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.3/unittest/suite.py", line 105, in run
    test(result)
  File "/usr/lib64/python3.3/unittest/suite.py", line 67, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.3/unittest/suite.py", line 105, in run
    test(result)
  File "/usr/lib64/python3.3/unittest/case.py", line 492, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.3/unittest/case.py", line 452, in run
    result.addFailure(self, exc_info)
  File "/usr/lib64/python3.3/unittest/runner.py", line 75, in addFailure
    super(TextTestResult, self).addFailure(test, err)
  File "/usr/lib64/python3.3/unittest/result.py", line 17, in inner
    return method(self, *args, **kw)
  File "/usr/lib64/python3.3/unittest/result.py", line 121, in addFailure
    self.failures.append((test, self._exc_info_to_string(err, test)))
  File "/usr/lib64/python3.3/unittest/result.py", line 160, in _exc_info_to_string
    msgLines = traceback.format_exception(exctype, value, tb, length)
  File "/usr/lib64/python3.3/traceback.py", line 187, in format_exception
    list.extend(format_tb(tb, limit))
  File "/usr/lib64/python3.3/traceback.py", line 75, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/usr/lib64/python3.3/traceback.py", line 100, in extract_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib64/python3.3/linecache.py", line 15, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib64/python3.3/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib64/python3.3/linecache.py", line 126, in updatecache
    with tokenize.open(fullname) as fp:
AttributeError: 'module' object has no attribute 'open'
FAIL
test_py2exe (enchant.tests.TestPy2exe)
Test pyenchant running inside a py2exe executable. ... ok
test_GetSetParam (enchant.tests.TestBroker) ... ok
test_HasENUS (enchant.tests.TestBroker)
Test that the en_US language is available. ... ok
test_LangsAreAvail (enchant.tests.TestBroker)
Test whether all advertised languages are in fact available. ... FAIL
test_ProvOrdering (enchant.tests.TestBroker)
Test that provider ordering works correctly. ... warning: line 274: incompatible stripping characters and condition
warning: line 275: incompatible stripping characters and condition
warning: line 599: incompatible stripping characters and condition
warning: line 901: incompatible stripping characters and condition
warning: line 1309: incompatible stripping characters and condition
warning: line 1310: incompatible stripping characters and condition
warning: line 1311: incompatible stripping characters and condition
warning: line 1759: incompatible stripping characters and condition
warning: line 1760: incompatible stripping characters and condition
warning: line 1761: incompatible stripping characters and condition
warning: line 2119: incompatible stripping characters and condition
warning: line 274: incompatible stripping characters and condition
warning: line 275: incompatible stripping characters and condition
warning: line 599: incompatible stripping characters and condition
warning: line 901: incompatible stripping characters and condition
warning: line 1309: incompatible stripping characters and condition
warning: line 1310: incompatible stripping characters and condition
warning: line 1311: incompatible stripping characters and condition
warning: line 1759: incompatible stripping characters and condition
warning: line 1760: incompatible stripping characters and condition
warning: line 1761: incompatible stripping characters and condition
warning: line 2119: incompatible stripping characters and condition
warning: line 274: incompatible stripping characters and condition
warning: line 275: incompatible stripping characters and condition
warning: line 599: incompatible stripping characters and condition
warning: line 901: incompatible stripping characters and condition
warning: line 1309: incompatible stripping characters and condition
warning: line 1310: incompatible stripping characters and condition
warning: line 1311: incompatible stripping characters and condition
warning: line 1759: incompatible stripping characters and condition
warning: line 1760: incompatible stripping characters and condition
warning: line 1761: incompatible stripping characters and condition
warning: line 2119: incompatible stripping characters and condition
ok
test_ProvsAreAvail (enchant.tests.TestBroker)
Test whether all advertised providers are in fact available. ... FAIL
test_UnicodeTag (enchant.tests.TestBroker)
Test that unicode language tags are accepted ... ok
test_AddRemove (enchant.tests.TestDict)
Test adding/removing from default user dictionary. ... ok
test_DefaultLang (enchant.tests.TestDict)
Test behaviour of default language selection. ... ok
test_HasENUS (enchant.tests.TestDict)
Test that the en_US language is available through default broker. ... ok
test_broker (enchant.tests.TestDict)
Test that the dict's broker is set correctly. ... ok
test_check (enchant.tests.TestDict)
Test that check() works on some common words. ... ok
test_pickling (enchant.tests.TestDict)
Test that pickling doensn't corrupt internal state. ... ok
test_session (enchant.tests.TestDict)
Test that adding words to the session works as required. ... ok
test_suggest (enchant.tests.TestDict)
Test that suggest() gets simple suggestions right. ... ok
test_suggestHang1 (enchant.tests.TestDict)
Test whether suggest() hangs on some inputs (Bug #1404196) ... ok
test_tag (enchant.tests.TestDict)
Test that the dict's tag is set correctly. ... ok
test_unicode1 (enchant.tests.TestDict)
Test checking/suggesting for unicode strings ... ok
test_DWPWL (enchant.tests.TestPWL)
Test functionality of DictWithPWL. ... ok
test_DWPWL_empty (enchant.tests.TestPWL)
Test functionality of DictWithPWL using transient dicts. ... ok
test_PyPWL (enchant.tests.TestPWL)
Test our pure-python PWL implementation. ... ok
test_UnicodeCharsInPath (enchant.tests.TestPWL)
Test that unicode chars in PWL paths are accepted. ... ok
test_UnicodeFN (enchant.tests.TestPWL)
Test that unicode PWL filenames are accepted. ... ok
test_add (enchant.tests.TestPWL)
Test that adding words to a PWL works correctly. ... ok
test_check (enchant.tests.TestPWL)
Test that basic checking works for PWLs. ... ok
test_suggestions (enchant.tests.TestPWL)
Test getting suggestions from a PWL. ... ok
test_trim_suggestions (enchant.tests.TestUtils) ... /tmp/pyenchant/enchant/tests.py:416: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(trim_suggestions(word,suggs,40),["god","good","bad+"])
ok
test_docstrings (enchant.tests.TestDocStrings)
Test that all our docstrings are error-free. ... ERROR
test_basic (enchant.checker.tests.TestChecker)
Test a basic run of the SpellChecker class. ... ok
test_bug2785373 (enchant.checker.tests.TestChecker)
Testcases for bug #2785373. ... ok
test_chararray (enchant.checker.tests.TestChecker)
Test SpellChecker with a character array as input. ... FAIL
test_chunkers (enchant.checker.tests.TestChecker)
Test SpellChecker with the 'chunkers' argument. ... ok
test_chunkers_and_filters (enchant.checker.tests.TestChecker)
Test SpellChecker with the 'chunkers' and 'filters' arguments. ... ERROR
test_default_language (enchant.checker.tests.TestChecker) ... ok
test_filters (enchant.checker.tests.TestChecker)
Test SpellChecker with the 'filters' argument. ... ERROR
test_pwl (enchant.checker.tests.TestChecker)
Test checker loop with PWL. ... ok
test_replace_with_empty_string (enchant.checker.tests.TestChecker)
Testcase for replacing with an empty string (bug #10) ... /tmp/pyenchant/enchant/checker/tests.py:246: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(chkr.get_text(),". I   .")
ok
test_replace_with_shorter_string (enchant.checker.tests.TestChecker)
Testcase for replacing with a shorter string (bug #10) ... ok
test_unicode (enchant.checker.tests.TestChecker)
Test SpellChecker with a unicode string. ... ok
test_basic_tokenize (enchant.tokenize.tests.TestTokenization)
Simple regression test for basic white-space tokenization. ... ok
test_tokenize_strip (enchant.tokenize.tests.TestTokenization)
Test special-char-stripping edge-cases in basic_tokenize. ... ok
test_wrap_tokenizer (enchant.tokenize.tests.TestTokenization)
Test wrapping of one tokenizer with another. ... ok
test_bug1591450 (enchant.tokenize.tests.TestTokenizeEN)
Check for tokenization regressions identified in bug #1591450. ... ok
test_bug2785373 (enchant.tokenize.tests.TestTokenizeEN)
Testcases for bug #2785373 ... ok
test_finnish_text (enchant.tokenize.tests.TestTokenizeEN)
Test tokenizing some Finnish text. ... ok
test_tokenize_en (enchant.tokenize.tests.TestTokenizeEN)
Simple regression test for English tokenization. ... ok
test_unicodeBasic (enchant.tokenize.tests.TestTokenizeEN)
Test tokenization of a basic unicode string. ... ok
test_unicodeCombining (enchant.tokenize.tests.TestTokenizeEN)
Test tokenization with unicode combining symbols. ... ok
test_utf8_bytes (enchant.tokenize.tests.TestTokenizeEN)
Test tokenization of UTF8-encoded bytes (bug #2500184). ... ok
test_utf8_bytes_at_end (enchant.tokenize.tests.TestTokenizeEN)
Test tokenization of UTF8-encoded bytes at end of word. ... ok
test_utf8_bytes_in_an_array (enchant.tokenize.tests.TestTokenizeEN)
Test tokenization of UTF8-encoded bytes stored in an array. ... ok
test_CombinedFilter (enchant.tokenize.tests.TestFilters)
Test several filters combined ... ok
test_EmailFilter (enchant.tokenize.tests.TestFilters)
Test filtering of email addresses ... ok
test_URLFilter (enchant.tokenize.tests.TestFilters)
Test filtering of URLs ... ok
test_WikiWordFilter (enchant.tokenize.tests.TestFilters)
Test filtering of WikiWords ... ok

======================================================================
ERROR: test_docstrings (enchant.tests.TestDocStrings)
Test that all our docstrings are error-free.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 398, in next
    (word,pos) = next(self._curtok)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 132, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 227, in next
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 398, in next
    (word,pos) = next(self._curtok)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 132, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 227, in next
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tests.py", line 469, in test_docstrings
    newobjs = list(self._check_docstrings(obj,errors))
  File "/tmp/pyenchant/enchant/tests.py", line 478, in _check_docstrings
    for err in chkr:
  File "/tmp/pyenchant/enchant/checker/__init__.py", line 230, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/checker/__init__.py", line 251, in next
    (word,pos) = next(self._tokens)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 392, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 401, in next
    (word,pos) = next(self._tokenizer)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 392, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 402, in next
    while self._skip(word):
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 445, in _skip
    if self._pattern.match(word):
TypeError: buffer size mismatch

======================================================================
ERROR: test_chunkers_and_filters (enchant.checker.tests.TestChecker)
Test SpellChecker with the 'chunkers' and 'filters' arguments.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 398, in next
    (word,pos) = next(self._curtok)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 132, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 227, in next
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 398, in next
    (word,pos) = next(self._curtok)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 132, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 227, in next
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/checker/tests.py", line 129, in test_chunkers_and_filters
    for err in chkr:
  File "/tmp/pyenchant/enchant/checker/__init__.py", line 230, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/checker/__init__.py", line 251, in next
    (word,pos) = next(self._tokens)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 392, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 401, in next
    (word,pos) = next(self._tokenizer)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 392, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 402, in next
    while self._skip(word):
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 445, in _skip
    if self._pattern.match(word):
TypeError: buffer size mismatch

======================================================================
ERROR: test_filters (enchant.checker.tests.TestChecker)
Test SpellChecker with the 'filters' argument.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 398, in next
    (word,pos) = next(self._curtok)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 132, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 227, in next
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 398, in next
    (word,pos) = next(self._curtok)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 132, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 227, in next
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/checker/tests.py", line 105, in test_filters
    for err in chkr:
  File "/tmp/pyenchant/enchant/checker/__init__.py", line 230, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/checker/__init__.py", line 251, in next
    (word,pos) = next(self._tokens)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 392, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 401, in next
    (word,pos) = next(self._tokenizer)
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 392, in __next__
    return self.next()
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 402, in next
    while self._skip(word):
  File "/tmp/pyenchant/enchant/tokenize/__init__.py", line 459, in _skip
    if self._pattern.match(word):
TypeError: buffer size mismatch

======================================================================
FAIL: test_UnicodeInstallPath (enchant.tests.TestInstallEnv)
Test installation in a path containing unicode chars.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tests.py", line 550, in test_UnicodeInstallPath
    self.runtests()
  File "/tmp/pyenchant/enchant/tests.py", line 538, in runtests
    self.assertEqual(res,0)
AssertionError: 1 != 0

======================================================================
FAIL: test_basic (enchant.tests.TestInstallEnv)
Test proper functioning of TestInstallEnv suite.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tests.py", line 543, in test_basic
    self.runtests()
  File "/tmp/pyenchant/enchant/tests.py", line 538, in runtests
    self.assertEqual(res,0)
AssertionError: 1 != 0

======================================================================
FAIL: test_LangsAreAvail (enchant.tests.TestBroker)
Test whether all advertised languages are in fact available.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tests.py", line 86, in test_LangsAreAvail
    assert False, "language '"+lang+"' advertised but non-existent"
AssertionError: language 'ru_RU_yo' advertised but non-existent

======================================================================
FAIL: test_ProvsAreAvail (enchant.tests.TestBroker)
Test whether all advertised providers are in fact available.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/tests.py", line 91, in test_ProvsAreAvail
    self.assertTrue(self.broker.dict_exists(lang))
AssertionError: False is not true

======================================================================
FAIL: test_chararray (enchant.checker.tests.TestChecker)
Test SpellChecker with a character array as input.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyenchant/enchant/checker/tests.py", line 189, in test_chararray
    self.assertEqual(err.word,"aray")
AssertionError: 'stord' != 'aray'
- stord
+ aray


----------------------------------------------------------------------
Ran 57 tests in 11.653s

FAILED (failures=5, errors=3)
```

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
