### ISSUE TITLE
Python 3: byte string in exception message

### ISSUE THREAD

**Issue by jwilk** [rfk/pyenchant#68]
```
$ python3 -c "import enchant as e; e.Dict('moo-oo-oo')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jwilk/pyenchant/enchant/__init__.py", line 558, in __init__
    _EnchantObject.__init__(self)
  File "/home/jwilk/pyenchant/enchant/__init__.py", line 168, in __init__
    self._init_this()
  File "/home/jwilk/pyenchant/enchant/__init__.py", line 565, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "/home/jwilk/pyenchant/enchant/__init__.py", line 310, in _request_dict_data
    self._raise_error(eStr % (tag,),DictNotFoundError)
  File "/home/jwilk/pyenchant/enchant/__init__.py", line 259, in _raise_error
    raise eclass(err)
enchant.errors.DictNotFoundError: b'invalid tag character found'
```

I'd expect the exception message to be a normal string, i.e.:
```
enchant.errors.DictNotFoundError: invalid tag character found
```

**Comment by rfk** [comment]
Thanks, should be fixed by https://github.com/rfk/pyenchant/commit/51e3f9286d6c4d6dab752b38eb891cf2027d1dc8
