### ISSUE TITLE
get_param broken in python3.x (NoneType decode error)

### ISSUE THREAD

**Issue by halfak** [rfk/pyenchant#88]
```
$ python
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> enchant.get_param("enchant.myspell.dictionary.path")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/halfak/venv/3.5/lib/python3.5/site-packages/enchant/__init__.py", line 479, in get_param
    return name.decode(_e.broker_get_param(self._this,name.encode()))
  File "/home/halfak/venv/3.5/lib/python3.5/site-packages/enchant/utils.py", line 170, in decode
    return value.decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by rfk** [comment]
Thanks for the report, looks like the underlying `broker_get_param` call may be returning None.
